# Generated by Django 6.1.1 on 2026-09-14 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigation', 'Under Investigation'), ('pending', 'Pending'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('incident_datetime', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('initial_facts', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('digital', 'Digital Evidence'), ('physical', 'Physical Evidence'), ('other', 'Other')], default='document', max_length=30)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/%d/')),
                ('source_reference', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='chatbot.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('purvanichargesheet', 'Purvani Chargesheet'), ('medicaltreatmentletter', 'Medical Treatment Letter'), ('policecustodyremandrequest', 'Police Custody Remand Request'), ('seizurereceipt', 'Seizure Receipt'), ('courtcustodyletter', 'Court Custody Letter'), ('accusedpanchanama', 'Accused Panchanama'), ('accusedfaceidentificationform', 'Accused Face Identification Form')], max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('under_review', 'Under Review'), ('reviewed', 'Reviewed'), ('revision_requested', 'Revision Requested')], default='generated', max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='generated_documents/%Y/%m/%d/')),
                ('generated_by', models.CharField(blank=True, max_length=255)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='chatbot.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(choices=[('bns', 'BNS'), ('bnss', 'BNSS'), ('bsa', 'BSA'), ('judgment', 'Judgment')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('provision', models.CharField(blank=True, max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=500)),
                ('source_reference', models.CharField(blank=True, max_length=500)),
                ('confidence', models.CharField(blank=True, max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_results', to='chatbot.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('complainant', 'Complainant'), ('victim', 'Victim'), ('accused', 'Accused'), ('witness', 'Witness'), ('officer', 'Officer'), ('other', 'Other')], default='other', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='chatbot.case')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('major', 'Major Event'), ('investigation', 'Investigation'), ('evidence', 'Evidence'), ('procedural', 'Procedural'), ('court', 'Court'), ('other', 'Other')], default='investigation', max_length=30)),
                ('datetime', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('officer', models.CharField(blank=True, max_length=255)),
                ('source_reference', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='chatbot.case')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
